### ISSUE TITLE
Minimal UI suggestion

### ISSUE THREAD

**Issue by purprika** [animify/colorbook#1]
Wouldn't you agree that it looks much better without the white borders around the colour circles?
That way the colours seamlessly merge together without interruption and we could have a better view how they would work in group. Less is more hé ;)

<img width="959" alt="screen shot 2018-01-03 at 17 06 17" src="https://user-images.githubusercontent.com/35072478/34529347-e4973cf8-f0ab-11e7-9731-400662318d99.png">

**Comment by animify** [comment]
Was having a debate about this myself! I agree about the color grouping, makes total sense.

I'll make the change for the upcoming update till I find a way to differentiate dark colors from the dark body background.

**Comment by purprika** [comment]
Very nice idea btw, i like the simplicity the site offers.
Maybe this would be a solution:
The dark colours get contrast from the other colours but when you hover or tap every colour that is dark gray or blackish you could give a border like your tooltip.
Just my 2 cents ;)
<img width="904" alt="screen shot 2018-01-03 at 18 10 35" src="https://user-images.githubusercontent.com/35072478/34531644-524be918-f0b3-11e7-9a44-ad1ea952cb07.png">
![screen-shot-2018-01-03-at-18 01 54](https://user-images.githubusercontent.com/35072478/34531674-6393024c-f0b3-11e7-9b7e-f885e612cb17.jpg)

**Comment by animify** [comment]
Thanks, that's the end goal, simple and to the point :)

Could work! Will have to look further into it, appreciate the suggestion nonetheless.

**Comment by purprika** [comment]
You're welcome, maybe with a little more thought you could figure something
out ;)

Cheers


[image: Logo]

MUSTAPHA EL BACHIRI
INTERACTIVE DESIGNER
[image: Phone] +32 471 72 79 36 [image: Email] mustapha@zhen.guru [image:
Web] www.zhen.guru

2018-01-03 18:31 GMT+01:00 Stefan Mansson <notifications@github.com>:
