### ISSUE TITLE
Copy Hex Colour Code when clicking on colour palettes

### ISSUE THREAD

**Issue by dazcro** [animify/colorbook#2]
Hi, 

What would be great is if you can copy the hex colour code to your clipboard when you click on the colour palettes.

![screen shot 2018-01-05 at 11 07 49 am](https://user-images.githubusercontent.com/25233409/34590097-b87fc410-f208-11e7-8526-e05d595ee66e.png)

**Comment by animify** [comment]
Hey, you can currently do that on the popular/timeline pages (no visual aid at the moment) but the full functionality is coming by the end of the week! Thanks!

**Comment by animify** [comment]
Update now live!
